# Form implementation generated from reading ui file 'src/ErrorDialog/ErrorDialog.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ErrorDialog(object):
    def setupUi(self, ErrorDialog, errorMessage):
        ErrorDialog.setObjectName("ErrorDialog")
        ErrorDialog.resize(577, 250)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resources/icons/error.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ErrorDialog.setWindowIcon(icon)
        ErrorDialog.setAccessibleName("")
        ErrorDialog.setStyleSheet("QDialog#ErrorDialog {\n"
"    background-color: rgb(84, 84, 84)\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(ErrorDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ErrorIconLabel = QtWidgets.QLabel(ErrorDialog)
        self.ErrorIconLabel.setText("")
        self.ErrorIconLabel.setPixmap(QtGui.QPixmap("../resources/icons/error.png"))
        self.ErrorIconLabel.setScaledContents(False)
        self.ErrorIconLabel.setObjectName("ErrorIconLabel")
        self.horizontalLayout.addWidget(self.ErrorIconLabel)
        self.ErrorMessageLabel = QtWidgets.QLabel(ErrorDialog)
        self.ErrorMessageLabel.setStyleSheet("QLabel#ErrorMessageLabel {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"}")
        self.ErrorMessageLabel.setObjectName("ErrorMessageLabel")
        self.horizontalLayout.addWidget(self.ErrorMessageLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.OKButton = QtWidgets.QPushButton(ErrorDialog)
        self.OKButton.setStyleSheet("QPushButton#OKButton {\n"
"    margin-left: 180px;\n"
"    margin-right: 180px;\n"
"    padding-top: 10px;\n"
"    padding-bottom: 10px;\n"
"\n"
"    border-radius: 6px;\n"
"    border: 3px solid #54a4a6;\n"
"\n"
"    font-weight: 600;\n"
"    font-size: 14px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#OKButton:hover {\n"
"    border-color: #63C2C4;    \n"
"}\n"
"\n"
"QPushButton#OKButton:pressed {\n"
"    background-color: rgb(70, 70, 70)\n"
"}")
        self.OKButton.setObjectName("OKButton")
        self.verticalLayout.addWidget(self.OKButton)

        self.retranslateUi(ErrorDialog, errorMessage)
        self.OKButton.clicked.connect(ErrorDialog.close)
        QtCore.QMetaObject.connectSlotsByName(ErrorDialog)

    def retranslateUi(self, ErrorDialog, errorMessage):
        _translate = QtCore.QCoreApplication.translate
        ErrorDialog.setWindowTitle(_translate("ErrorDialog", "Greška"))
        self.ErrorMessageLabel.setText(_translate("ErrorDialog", errorMessage))
        self.OKButton.setText(_translate("ErrorDialog", "U redu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ErrorDialog = QtWidgets.QDialog()
    ui = Ui_ErrorDialog()
    ui.setupUi(ErrorDialog)
    ErrorDialog.show()
    sys.exit(app.exec())
