# Form implementation generated from reading ui file 'src/ProcessingDialog/ProcessingDialog.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from pathlib import Path

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QMovie


class Ui_ProcessingDialog(object):
    def setupUi(self, ProcessingDialog):
        ProcessingDialog.setObjectName("ProcessingDialog")
        ProcessingDialog.resize(577, 253)
        ProcessingDialog.setAccessibleName("")
        ProcessingDialog.setStyleSheet("QDialog#ProcessingDialog {\n"
"    background-color: rgb(84, 84, 84)\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(ProcessingDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(ProcessingDialog)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox.setStyleSheet("QGroupBox#groupBox {\n"
                                    "    border: 0;\n"
                                    "}")
        self.ProcessingMessageLabel = QtWidgets.QLabel(self.groupBox)
        self.ProcessingMessageLabel.setGeometry(QtCore.QRect(10, 50, 535, 30))
        self.ProcessingMessageLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.ProcessingMessageLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.ProcessingMessageLabel.setStyleSheet("QLabel#ProcessingMessageLabel {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"}")
        self.ProcessingMessageLabel.setObjectName("ProcessingMessageLabel")
        self.ProcessingAnimationLabel = QtWidgets.QLabel(self.groupBox)
        self.animation = QMovie("../resources/animations/loading.gif")
        self.ProcessingAnimationLabel.setStyleSheet("QLabel#ProcessingAnimationLabel {\n"
                                                    "    padding-left: 25px;\n"
                                                    "    padding-top: 0px;\n"
                                                    "    margin-top: 0px;\n"

                                                    "}")
        self.ProcessingAnimationLabel.setMovie(self.animation)
        self.animation.start()
        self.ProcessingAnimationLabel.setGeometry(QtCore.QRect(10, 0, 541, 200))
        self.ProcessingAnimationLabel.setMinimumSize(QtCore.QSize(0, 190))
        self.ProcessingAnimationLabel.setMaximumSize(QtCore.QSize(16777215, 200))
        self.ProcessingAnimationLabel.setText("")
        self.ProcessingAnimationLabel.setScaledContents(False)
        self.ProcessingAnimationLabel.setObjectName("ProcessingAnimationLabel")

        self.verticalLayout.addWidget(self.groupBox)

        self.StopButton = QtWidgets.QPushButton(ProcessingDialog)
        self.StopButton.setStyleSheet("QPushButton#StopButton {\n"
"    margin-left: 180px;\n"
"    margin-right: 180px;\n"
"    padding-top: 10px;\n"
"    padding-bottom: 10px;\n"
"\n"
"    border-radius: 6px;\n"
"    border: 3px solid #9C8ABF;\n"
"\n"
"    font-weight: 600;\n"
"    font-size: 14px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#StopButton:hover {\n"
"    border-color: #B8A2E1;    \n"
"}\n"
"\n"
"QPushButton#StopButton:pressed {\n"
"    background-color: rgb(70, 70, 70)\n"
"}")
        self.StopButton.setObjectName("StopButton")
        self.verticalLayout.addWidget(self.StopButton)

        self.retranslateUi(ProcessingDialog)
        self.StopButton.clicked.connect(ProcessingDialog.close)
        QtCore.QMetaObject.connectSlotsByName(ProcessingDialog)

    def retranslateUi(self, ProcessingDialog):
        _translate = QtCore.QCoreApplication.translate
        ProcessingDialog.setWindowTitle(_translate("ProcessingDialog", "..."))
        self.ProcessingMessageLabel.setText(_translate("ProcessingDialog", "<html><head/><body><p align=\"center\">Obrada audio datoteke u tijeku.</p><p align=\"center\"><br/></p></body></html>"))
        self.StopButton.setText(_translate("ProcessingDialog", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProcessingDialog = QtWidgets.QDialog()
    ui = Ui_ProcessingDialog()
    ui.setupUi(ProcessingDialog)
    ProcessingDialog.show()
    sys.exit(app.exec())
