# Form implementation generated from reading ui file 'src/View/ProcessingDialog/ProcessingDialog.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QMovie


class Ui_ProcessingDialog(object):
    def setupUi(self, ProcessingDialog):
        ProcessingDialog.setObjectName("ProcessingDialog")
        ProcessingDialog.resize(570, 226)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/View/ProcessingDialog/../../resources/icons/error.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ProcessingDialog.setWindowIcon(icon)
        ProcessingDialog.setAccessibleName("")
        ProcessingDialog.setStyleSheet("QDialog#ProcessingDialog {\n"
"    background-color: rgb(84, 84, 84)\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(ProcessingDialog)
        self.verticalLayout.setContentsMargins(15, 20, 15, 20)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(ProcessingDialog)
        self.groupBox.setEnabled(False)
        self.groupBox.setStyleSheet("QGroupBox#groupBox {\n"
"    border: 0;\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.ProcessingMessageLabel = QtWidgets.QLabel(self.groupBox)
        self.ProcessingMessageLabel.setGeometry(QtCore.QRect(10, 20, 535, 30))
        self.ProcessingMessageLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.ProcessingMessageLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.ProcessingMessageLabel.setStyleSheet("QLabel#ProcessingMessageLabel {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"}")
        self.ProcessingMessageLabel.setObjectName("ProcessingMessageLabel")
        self.ProcessingAnimationLabel = QtWidgets.QLabel(self.groupBox)
        self.ProcessingAnimationLabel.setGeometry(QtCore.QRect(0, -10, 541, 200))
        self.ProcessingAnimationLabel.setMinimumSize(QtCore.QSize(0, 190))
        self.ProcessingAnimationLabel.setMaximumSize(QtCore.QSize(16777215, 200))
        self.animation = QMovie("skripta/resources/animations/loading.gif")
        self.ProcessingAnimationLabel.setStyleSheet("QLabel#ProcessingAnimationLabel {\n"
"    padding-right: 20px;\n"
"    padding-bottom: 35px;\n"
"}")
        self.ProcessingAnimationLabel.setMovie(self.animation)
        self.animation.start()
        self.ProcessingAnimationLabel.setText("")
        self.ProcessingAnimationLabel.setScaledContents(False)
        self.ProcessingAnimationLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ProcessingAnimationLabel.setObjectName("ProcessingAnimationLabel")
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.StopButton = QtWidgets.QPushButton(ProcessingDialog)
        self.StopButton.setMinimumSize(QtCore.QSize(135, 30))
        self.StopButton.setMaximumSize(QtCore.QSize(135, 30))
        self.StopButton.setStyleSheet("QPushButton#StopButton {\n"
"    border-radius: 6px;\n"
"    border: 3px solid #9C8ABF;\n"
"\n"
"    font-weight: 600;\n"
"    font-size: 14px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#StopButton:hover {\n"
"    border-color: #B8A2E1;    \n"
"}\n"
"\n"
"QPushButton#StopButton:pressed {\n"
"    background-color: rgb(70, 70, 70)\n"
"}")
        self.StopButton.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText)
        self.StopButton.setDefault(False)
        self.StopButton.setObjectName("StopButton")
        self.horizontalLayout.addWidget(self.StopButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(ProcessingDialog)
        self.StopButton.clicked.connect(ProcessingDialog.close)
        QtCore.QMetaObject.connectSlotsByName(ProcessingDialog)

    def retranslateUi(self, ProcessingDialog):
        _translate = QtCore.QCoreApplication.translate
        ProcessingDialog.setWindowTitle(_translate("ProcessingDialog", "..."))
        self.ProcessingMessageLabel.setText(_translate("ProcessingDialog", "<html><head/><body><p align=\"center\">Obrada audio datoteke u tijeku.</p><p align=\"center\"><br/></p></body></html>"))
        self.StopButton.setText(_translate("ProcessingDialog", "Stop"))

    def setText(self, message):
        _translate = QtCore.QCoreApplication.translate
        self.ProcessingMessageLabel.setText(_translate("ProcessingDialog", message))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProcessingDialog = QtWidgets.QDialog()
    ui = Ui_ProcessingDialog()
    ui.setupUi(ProcessingDialog)
    ProcessingDialog.show()
    sys.exit(app.exec())
