# Form implementation generated from reading ui file 'src/View/ErrorDialog/ErrorDialog.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ErrorDialog(object):
    def setupUi(self, ErrorDialog):
        ErrorDialog.setObjectName("ErrorDialog")
        ErrorDialog.resize(570, 225)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("skripta/resources/icons/error.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ErrorDialog.setWindowIcon(icon)
        ErrorDialog.setAccessibleName("")
        ErrorDialog.setStyleSheet("QDialog#ErrorDialog {\n"
"    background-color: rgb(84, 84, 84)\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(ErrorDialog)
        self.verticalLayout.setContentsMargins(15, 20, 15, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ErrorIconLabel = QtWidgets.QLabel(ErrorDialog)
        self.ErrorIconLabel.setText("")
        self.ErrorIconLabel.setPixmap(QtGui.QPixmap("skripta/resources/icons/error.png"))
        self.ErrorIconLabel.setScaledContents(False)
        self.ErrorIconLabel.setObjectName("ErrorIconLabel")
        self.horizontalLayout.addWidget(self.ErrorIconLabel)
        self.ErrorMessageLabel = QtWidgets.QLabel(ErrorDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ErrorMessageLabel.sizePolicy().hasHeightForWidth())
        self.ErrorMessageLabel.setSizePolicy(sizePolicy)
        self.ErrorMessageLabel.setStyleSheet("QLabel#ErrorMessageLabel {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"}")
        self.ErrorMessageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.ErrorMessageLabel.setWordWrap(True)
        self.ErrorMessageLabel.setObjectName("ErrorMessageLabel")
        self.horizontalLayout.addWidget(self.ErrorMessageLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.OKButton = QtWidgets.QPushButton(ErrorDialog)
        self.OKButton.setMinimumSize(QtCore.QSize(135, 30))
        self.OKButton.setStyleSheet("QPushButton#OKButton {\n"
"    border-radius: 6px;\n"
"    border: 3px solid #54a4a6;\n"
"\n"
"    font-weight: 600;\n"
"    font-size: 14px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#OKButton:hover {\n"
"    border-color: #63C2C4;    \n"
"}\n"
"\n"
"QPushButton#OKButton:pressed {\n"
"    background-color: rgb(70, 70, 70)\n"
"}")
        self.OKButton.setObjectName("OKButton")
        self.horizontalLayout_2.addWidget(self.OKButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(ErrorDialog)
        self.OKButton.clicked.connect(ErrorDialog.close)
        QtCore.QMetaObject.connectSlotsByName(ErrorDialog)

    def retranslateUi(self, ErrorDialog):
        _translate = QtCore.QCoreApplication.translate
        ErrorDialog.setWindowTitle(_translate("ErrorDialog", "Greška"))
        self.ErrorMessageLabel.setText(_translate("ErrorDialog", "Greška"))
        self.OKButton.setText(_translate("ErrorDialog", "U redu"))

    def setText(self, message):
        _translate = QtCore.QCoreApplication.translate
        self.ErrorMessageLabel.setText(_translate("ErrorDialog", message))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ErrorDialog = QtWidgets.QDialog()
    ui = Ui_ErrorDialog()
    ui.setupUi(ErrorDialog)
    ErrorDialog.show()
    sys.exit(app.exec())
