# Form implementation generated from reading ui file 'src/View/ResultDialog/ResultDialog.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ResultDialog(object):
    def setupUi(self, ResultDialog):
        ResultDialog.setObjectName("ResultDialog")
        ResultDialog.resize(620, 735)
        ResultDialog.setMinimumSize(QtCore.QSize(620, 735))
        ResultDialog.setMaximumSize(QtCore.QSize(620, 735))
        ResultDialog.setStyleSheet("QDialog {\n"
"    background-color: rgb(84, 84, 84);\n"
"}")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(ResultDialog)
        self.verticalLayout_3.setContentsMargins(15, 20, 15, 20)
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(ResultDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    border: none;\n"
"    max-height: 75px;\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.resultLabel = QtWidgets.QLabel(self.groupBox)
        self.resultLabel.setStyleSheet("")
        self.resultLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.resultLabel.setObjectName("resultLabel")
        self.verticalLayout_2.addWidget(self.resultLabel)
        self.editLabel = QtWidgets.QLabel(self.groupBox)
        self.editLabel.setStyleSheet("")
        self.editLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.editLabel.setObjectName("editLabel")
        self.verticalLayout_2.addWidget(self.editLabel)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.frame = QtWidgets.QFrame(ResultDialog)
        self.frame.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.resultTextEdit = QtWidgets.QPlainTextEdit(self.frame)
        self.resultTextEdit.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.resultTextEdit.setStyleSheet("QPlainTextEdit {\n"
"    background-color: rgb(84, 84, 84);\n"
"    border-none;    \n"
"    border: 0.5px solid #54a4a6;\n"
"    border-radius: 0px;\n"
"    padding: 2px 2px 2px 2px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPlainTextEdit::hover {\n"
"    border-color: #63C2C4;\n"
"}\n"
"\n"
"QPlainTextEdit::disabled {\n"
"    color: rgb(153, 153, 153);\n"
"}")
        self.resultTextEdit.setObjectName("resultTextEdit")
        self.verticalLayout.addWidget(self.resultTextEdit)
        self.verticalLayout_3.addWidget(self.frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cancelButton = QtWidgets.QPushButton(ResultDialog)
        self.cancelButton.setMinimumSize(QtCore.QSize(135, 30))
        self.cancelButton.setStyleSheet("QPushButton {\n"
"    border-radius: 6px;\n"
"    border: 3px solid #9C8ABF;\n"
"\n"
"    font-weight: 600;\n"
"    font-size: 14px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   border-color: #B8A2E1;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(70, 70, 70)\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: rgb(153, 153, 153);\n"
"}")
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.saveButton = QtWidgets.QPushButton(ResultDialog)
        self.saveButton.setMinimumSize(QtCore.QSize(135, 30))
        self.saveButton.setStyleSheet("QPushButton {\n"
"    border-radius: 6px;\n"
"    border: 3px solid #54a4a6;\n"
"\n"
"    font-weight: 600;\n"
"    font-size: 14px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   border-color: #63C2C4;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(70, 70, 70)\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: rgb(153, 153, 153);\n"
"}")
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 6)
        self.verticalLayout_3.setStretch(2, 1)

        self.retranslateUi(ResultDialog)
        self.cancelButton.clicked.connect(ResultDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ResultDialog)

    def retranslateUi(self, ResultDialog):
        _translate = QtCore.QCoreApplication.translate
        ResultDialog.setWindowTitle(_translate("ResultDialog", "Rezultat"))
        self.resultLabel.setText(_translate("ResultDialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:700; color:#ffffff;\">Nova skripta!</span></p></body></html>"))
        self.editLabel.setText(_translate("ResultDialog", "<html><head/><body><p><span style=\" font-size:11pt; color:#ffffff;\">Pregledaj i uredi transkript prije spremanja.</span></p></body></html>"))
        self.cancelButton.setText(_translate("ResultDialog", "Odustani"))
        self.saveButton.setText(_translate("ResultDialog", "Spremi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ResultDialog = QtWidgets.QDialog()
    ui = Ui_ResultDialog()
    ui.setupUi(ResultDialog)
    ResultDialog.show()
    sys.exit(app.exec())
