# Form implementation generated from reading ui file 'src/SuccessDialog/SuccessDialog.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SuccessDialog(object):
    def setupUi(self, SuccessDialog):
        SuccessDialog.setObjectName("SuccessDialog")
        SuccessDialog.resize(597, 250)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/SuccessDialog/../../../../../../resources/icons/error.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        SuccessDialog.setWindowIcon(icon)
        SuccessDialog.setAccessibleName("")
        SuccessDialog.setStyleSheet("QDialog#SuccessDialog {\n"
"    background-color: rgb(84, 84, 84)\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(SuccessDialog)
        self.verticalLayout.setSpacing(45)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(20, 25, 50, -1)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SuccessIconLabel = QtWidgets.QLabel(SuccessDialog)
        self.SuccessIconLabel.setText("")
        self.SuccessIconLabel.setPixmap(QtGui.QPixmap("../resources/icons/success.png"))
        self.SuccessIconLabel.setScaledContents(False)
        self.SuccessIconLabel.setObjectName("SuccessIconLabel")
        self.horizontalLayout.addWidget(self.SuccessIconLabel)
        self.SuccessMessageLabel = QtWidgets.QLabel(SuccessDialog)
        self.SuccessMessageLabel.setStyleSheet("QLabel#SuccessMessageLabel {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"}")
        self.SuccessMessageLabel.setObjectName("SuccessMessageLabel")
        self.horizontalLayout.addWidget(self.SuccessMessageLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.OpenFileButton = QtWidgets.QPushButton(SuccessDialog)
        self.OpenFileButton.setStyleSheet("QPushButton#OpenFileButton {\n"
"    margin-left: 100px;\n"
"    padding-top: 10px;\n"
"    padding-bottom: 10px;\n"
"\n"
"    border-radius: 6px;\n"
"    border: 3px solid #9C8ABF;\n"
"\n"
"    font-weight: 600;\n"
"    font-size: 14px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#OpenFileButton:hover {\n"
"    border-color: #B8A2E1;    \n"
"}\n"
"\n"
"QPushButton#OpenFileButton:pressed {\n"
"    background-color: rgb(70, 70, 70)\n"
"}")
        self.OpenFileButton.setObjectName("OpenFileButton")
        self.horizontalLayout_2.addWidget(self.OpenFileButton)
        self.OKButton = QtWidgets.QPushButton(SuccessDialog)
        self.OKButton.setStyleSheet("QPushButton#OKButton {\n"
"    margin-right: 100px;\n"
"    padding-top: 10px;\n"
"    padding-bottom: 10px;\n"
"\n"
"    border-radius: 6px;\n"
"    border: 3px solid #54a4a6;\n"
"\n"
"    font-weight: 600;\n"
"    font-size: 14px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#OKButton:hover {\n"
"    border-color: #63C2C4;    \n"
"}\n"
"\n"
"QPushButton#OKButton:pressed {\n"
"    background-color: rgb(70, 70, 70)\n"
"}")
        self.OKButton.setObjectName("OKButton")
        self.horizontalLayout_2.addWidget(self.OKButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(SuccessDialog)
        self.OKButton.clicked.connect(SuccessDialog.close)
        QtCore.QMetaObject.connectSlotsByName(SuccessDialog)

    def retranslateUi(self, SuccessDialog):
        _translate = QtCore.QCoreApplication.translate
        SuccessDialog.setWindowTitle(_translate("SuccessDialog", "Uspjeh"))
        self.SuccessMessageLabel.setText(_translate("SuccessDialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Audio datoteka je uspješno transkribirana!</span></p></body></html>"))
        self.OpenFileButton.setText(_translate("SuccessDialog", "Otvori"))
        self.OKButton.setText(_translate("SuccessDialog", "U redu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SuccessDialog = QtWidgets.QDialog()
    ui = Ui_SuccessDialog()
    ui.setupUi(SuccessDialog)
    SuccessDialog.show()
    sys.exit(app.exec())
