# Form implementation generated from reading ui file 'src/View/MicOptionsDialog/MicOptionsDialog.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OptionsDialog(object):
    def setupUi(self, OptionsDialog):
        OptionsDialog.setObjectName("OptionsDialog")
        OptionsDialog.resize(620, 758)
        OptionsDialog.setStyleSheet("QDialog#OptionsDialog {\n"
"    background-color: rgb(84, 84, 84);\n"
"}")
        OptionsDialog.setModal(False)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(OptionsDialog)
        self.verticalLayout_4.setContentsMargins(15, 20, 15, 20)
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(OptionsDialog)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.frame = QtWidgets.QFrame(OptionsDialog)
        self.frame.setStyleSheet("QFrame {\n"
"padding-right: 5px;\n"
"padding-top: 5px;\n"
"padding-bottom: 5px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fileHLayout = QtWidgets.QHBoxLayout()
        self.fileHLayout.setObjectName("fileHLayout")
        self.micLabel = QtWidgets.QLabel(self.frame)
        self.micLabel.setObjectName("micLabel")
        self.fileHLayout.addWidget(self.micLabel)
        self.micComboBox = QtWidgets.QComboBox(self.frame)
        self.micComboBox.setStyleSheet("QComboBox {\n"
"    background-color: rgb(84, 84, 84);\n"
"    border-none;    \n"
"    border-bottom: 0.5px solid #54a4a6;\n"
"    border-radius: 0px;\n"
"    padding: 2px 2px 2px 2px;\n"
"    color: white;\n"
"}\n"
"\n"
"QComboBox::hover {\n"
"    border-color: #63C2C4;\n"
"}\n"
"\n"
"QComboBox::disabled {\n"
"    color: rgb(153, 153, 153);\n"
"}\n"
"\n"
"\n"
"/*  After dropping, the entire drop-down form style */\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid white;   /*  Border of the entire drop-down form */\n"
"    background-color: rgb(84, 84, 84);;   /*  Whole drop-down form background color */\n"
"    color: white;\n"
"    padding: 2px 2px 2px 2px;\n"
"}\n"
"\n"
"/*  Down pull, the entire drop-down window */\n"
"QComboBox QAbstractItemView::item {\n"
"    height: 25px;   /*  The height of the item (set pcomboBox-> setView (new qlistview ()); after this item works) */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    border: none;\n"
"    border-top: 0.5px solid rgb(81, 81, 81);\n"
"    border-bottom: 0.5px solid rgb(81, 81, 81);\n"
"    border-radius: 2px;\n"
"    background-color: rgb(84, 84, 84);\n"
"}")
        self.micComboBox.setEditable(True)
        self.micComboBox.setMaxVisibleItems(5)
        self.micComboBox.setObjectName("micComboBox")
        self.fileHLayout.addWidget(self.micComboBox)
        self.verticalLayout.addLayout(self.fileHLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.apiLabel = QtWidgets.QLabel(self.frame)
        self.apiLabel.setObjectName("apiLabel")
        self.horizontalLayout.addWidget(self.apiLabel)
        self.apiComboBox = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apiComboBox.sizePolicy().hasHeightForWidth())
        self.apiComboBox.setSizePolicy(sizePolicy)
        self.apiComboBox.setStyleSheet("QComboBox {\n"
"    background-color: rgb(84, 84, 84);\n"
"    border-none;    \n"
"    border-bottom: 0.5px solid #54a4a6;\n"
"    border-radius: 0px;\n"
"    padding: 2px 2px 2px 2px;\n"
"    color: white;\n"
"}\n"
"\n"
"QComboBox::hover {\n"
"    border-color: #63C2C4;\n"
"}\n"
"\n"
"/*  After dropping, the entire drop-down form style */\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid white;   /*  Border of the entire drop-down form */\n"
"    background-color: rgb(84, 84, 84);;   /*  Whole drop-down form background color */\n"
"    selection-background-color: lightgreen;   /*  The whole drop-down window is selected from the background color of the item */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    height: 70px; \n"
"}")
        self.apiComboBox.setEditable(False)
        self.apiComboBox.setObjectName("apiComboBox")
        self.apiComboBox.addItem("")
        self.apiComboBox.addItem("")
        self.apiComboBox.addItem("")
        self.apiComboBox.addItem("")
        self.horizontalLayout.addWidget(self.apiComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.timeHLayout = QtWidgets.QHBoxLayout()
        self.timeHLayout.setSpacing(6)
        self.timeHLayout.setObjectName("timeHLayout")
        self.durationLabel = QtWidgets.QLabel(self.frame)
        self.durationLabel.setMinimumSize(QtCore.QSize(125, 0))
        self.durationLabel.setObjectName("durationLabel")
        self.timeHLayout.addWidget(self.durationLabel)
        self.durationLineEdit = QtWidgets.QLineEdit(self.frame)
        self.durationLineEdit.setEnabled(True)
        self.durationLineEdit.setMaximumSize(QtCore.QSize(61, 16777215))
        self.durationLineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(84, 84, 84);\n"
"    border-none;    \n"
"    border-bottom: 0.5px solid #54a4a6;\n"
"    border-radius: 0px;\n"
"    padding: 2px 2px 2px 2px;\n"
"    color: white;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border-color: #63C2C4;\n"
"}")
        self.durationLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhTime)
        self.durationLineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.durationLineEdit.setDragEnabled(False)
        self.durationLineEdit.setObjectName("durationLineEdit")
        self.timeHLayout.addWidget(self.durationLineEdit)
        self.verticalLayout.addLayout(self.timeHLayout)
        self.verticalLayout_4.addWidget(self.frame)
        self.label_3 = QtWidgets.QLabel(OptionsDialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.frame_3 = QtWidgets.QFrame(OptionsDialog)
        self.frame_3.setStyleSheet("QFrame {\n"
"\n"
"padding-right: 5px;\n"
"padding-top: 5px;\n"
"padding-bottom: 5px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.noiseHLayout = QtWidgets.QHBoxLayout()
        self.noiseHLayout.setSpacing(6)
        self.noiseHLayout.setObjectName("noiseHLayout")
        self.noiseTypeLabel = QtWidgets.QLabel(self.frame_3)
        self.noiseTypeLabel.setObjectName("noiseTypeLabel")
        self.noiseHLayout.addWidget(self.noiseTypeLabel)
        self.noiseTypeComboBox = QtWidgets.QComboBox(self.frame_3)
        self.noiseTypeComboBox.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.PreventContextMenu)
        self.noiseTypeComboBox.setStyleSheet("QComboBox {\n"
"    background-color: rgb(84, 84, 84);\n"
"    border-none;    \n"
"    border-bottom: 0.5px solid #54a4a6;\n"
"    border-radius: 0px;\n"
"    padding: 2px 2px 2px 2px;\n"
"    color: white;\n"
"}\n"
"\n"
"QComboBox::hover {\n"
"    border-color: #63C2C4;\n"
"}\n"
"\n"
"/*  After dropping, the entire drop-down form style */\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid white;   /*  Border of the entire drop-down form */\n"
"    background-color: rgb(84, 84, 84);;   /*  Whole drop-down form background color */\n"
"    selection-background-color: lightgreen;   /*  The whole drop-down window is selected from the background color of the item */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    height: 70px; \n"
"}")
        self.noiseTypeComboBox.setFrame(False)
        self.noiseTypeComboBox.setObjectName("noiseTypeComboBox")
        self.noiseTypeComboBox.addItem("")
        self.noiseTypeComboBox.addItem("")
        self.noiseTypeComboBox.addItem("")
        self.noiseHLayout.addWidget(self.noiseTypeComboBox)
        self.verticalLayout_3.addLayout(self.noiseHLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.noiseValueLabel = QtWidgets.QLabel(self.frame_3)
        self.noiseValueLabel.setEnabled(True)
        self.noiseValueLabel.setObjectName("noiseValueLabel")
        self.horizontalLayout_2.addWidget(self.noiseValueLabel)
        self.noiseValueLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.noiseValueLineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noiseValueLineEdit.sizePolicy().hasHeightForWidth())
        self.noiseValueLineEdit.setSizePolicy(sizePolicy)
        self.noiseValueLineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(84, 84, 84);\n"
"    border-none;    \n"
"    border-bottom: 0.5px solid #54a4a6;\n"
"    border-radius: 0px;\n"
"    padding: 2px 2px 2px 2px;\n"
"    color: white;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border-color: #63C2C4;\n"
"}\n"
"\n"
"QLineEdit::disabled {\n"
"    color: rgb(153, 153, 153);\n"
"}\n"
"")
        self.noiseValueLineEdit.setObjectName("noiseValueLineEdit")
        self.horizontalLayout_2.addWidget(self.noiseValueLineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.label_2 = QtWidgets.QLabel(OptionsDialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.frame_2 = QtWidgets.QFrame(OptionsDialog)
        self.frame_2.setStyleSheet("QFrame {\n"
"padding-right: 5px;\n"
"padding-top: 5px;\n"
"padding-bottom: 5px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.languageLabel = QtWidgets.QLabel(self.frame_2)
        self.languageLabel.setObjectName("languageLabel")
        self.horizontalLayout_3.addWidget(self.languageLabel)
        self.languageComboBox = QtWidgets.QComboBox(self.frame_2)
        self.languageComboBox.setEnabled(True)
        self.languageComboBox.setStyleSheet("QComboBox {\n"
"    background-color: rgb(84, 84, 84);\n"
"    border-none;    \n"
"    border-bottom: 0.5px solid #54a4a6;\n"
"    border-radius: 0px;\n"
"    padding: 2px 2px 2px 2px;\n"
"    color: white;\n"
"}\n"
"\n"
"QComboBox::hover {\n"
"    border-color: #63C2C4;\n"
"}\n"
"\n"
"QComboBox::disabled {\n"
"    color: rgb(153, 153, 153);\n"
"}\n"
"\n"
"\n"
"/*  After dropping, the entire drop-down form style */\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid white;   /*  Border of the entire drop-down form */\n"
"    background-color: rgb(84, 84, 84);;   /*  Whole drop-down form background color */\n"
"    color: white;\n"
"    padding: 2px 2px 2px 2px;\n"
"}\n"
"\n"
"/*  Down pull, the entire drop-down window */\n"
"QComboBox QAbstractItemView::item {\n"
"    height: 25px;   /*  The height of the item (set pcomboBox-> setView (new qlistview ()); after this item works) */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    border: none;\n"
"    border-top: 0.5px solid rgb(81, 81, 81);\n"
"    border-bottom: 0.5px solid rgb(81, 81, 81);\n"
"    border-radius: 2px;\n"
"    background-color: rgb(84, 84, 84);\n"
"}")
        self.languageComboBox.setEditable(True)
        self.languageComboBox.setObjectName("languageComboBox")
        self.horizontalLayout_3.addWidget(self.languageComboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.phrasesLabel = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phrasesLabel.sizePolicy().hasHeightForWidth())
        self.phrasesLabel.setSizePolicy(sizePolicy)
        self.phrasesLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.phrasesLabel.setObjectName("phrasesLabel")
        self.horizontalLayout_4.addWidget(self.phrasesLabel)
        self.phrasesTextEdit = QtWidgets.QPlainTextEdit(self.frame_2)
        self.phrasesTextEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phrasesTextEdit.sizePolicy().hasHeightForWidth())
        self.phrasesTextEdit.setSizePolicy(sizePolicy)
        self.phrasesTextEdit.setStyleSheet("QPlainTextEdit {\n"
"    background-color: rgb(84, 84, 84);\n"
"    border-none;    \n"
"    border: 0.5px solid #54a4a6;\n"
"    border-radius: 0px;\n"
"    padding: 2px 2px 2px 2px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPlainTextEdit::hover {\n"
"    border-color: #63C2C4;\n"
"}\n"
"\n"
"QPlainTextEdit::disabled {\n"
"    color: rgb(153, 153, 153);\n"
"}")
        self.phrasesTextEdit.setObjectName("phrasesTextEdit")
        self.horizontalLayout_4.addWidget(self.phrasesTextEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sensitivityLabel = QtWidgets.QLabel(self.frame_2)
        self.sensitivityLabel.setEnabled(False)
        self.sensitivityLabel.setObjectName("sensitivityLabel")
        self.horizontalLayout_5.addWidget(self.sensitivityLabel)
        self.sensitivityLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.sensitivityLineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensitivityLineEdit.sizePolicy().hasHeightForWidth())
        self.sensitivityLineEdit.setSizePolicy(sizePolicy)
        self.sensitivityLineEdit.setToolTip("")
        self.sensitivityLineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(84, 84, 84);\n"
"    border-none;    \n"
"    border-bottom: 0.5px solid #54a4a6;\n"
"    border-radius: 0px;\n"
"    padding: 2px 2px 2px 2px;\n"
"    color: white;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border-color:#63C2C4;\n"
"}\n"
"\n"
"QLineEdit::disabled {\n"
"    color: rgb(153, 153, 153);\n"
"}")
        self.sensitivityLineEdit.setObjectName("sensitivityLineEdit")
        self.horizontalLayout_5.addWidget(self.sensitivityLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.grammarLabel = QtWidgets.QLabel(self.frame_2)
        self.grammarLabel.setObjectName("grammarLabel")
        self.horizontalLayout_6.addWidget(self.grammarLabel)
        self.grammarLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.grammarLineEdit.setEnabled(False)
        self.grammarLineEdit.setMaximumSize(QtCore.QSize(400, 16777215))
        self.grammarLineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(84, 84, 84);\n"
"    border-none;    \n"
"    border-bottom: 0.5px solid #54a4a6;\n"
"    border-radius: 0px;\n"
"    padding: 2px 2px 2px 2px;\n"
"    color: white;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border-color:#63C2C4;\n"
"}")
        self.grammarLineEdit.setText("")
        self.grammarLineEdit.setClearButtonEnabled(True)
        self.grammarLineEdit.setObjectName("grammarLineEdit")
        self.horizontalLayout_6.addWidget(self.grammarLineEdit)
        self.browseGrammarButton = QtWidgets.QPushButton(self.frame_2)
        self.browseGrammarButton.setEnabled(False)
        self.browseGrammarButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.browseGrammarButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(84, 84, 84);\n"
"    border-color: white\n"
"}")
        self.browseGrammarButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("skripta/resources/icons/browse.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.browseGrammarButton.setIcon(icon)
        self.browseGrammarButton.setAutoDefault(False)
        self.browseGrammarButton.setObjectName("browseGrammarButton")
        self.horizontalLayout_6.addWidget(self.browseGrammarButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.hotwordLabel = QtWidgets.QLabel(self.frame_2)
        self.hotwordLabel.setObjectName("hotwordLabel")
        self.horizontalLayout_8.addWidget(self.hotwordLabel)
        self.hotwordsLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.hotwordsLineEdit.setMinimumSize(QtCore.QSize(400, 0))
        self.hotwordsLineEdit.setMaximumSize(QtCore.QSize(400, 16777215))
        self.hotwordsLineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(84, 84, 84);\n"
"    border-none;    \n"
"    border-bottom: 0.5px solid #54a4a6;\n"
"    border-radius: 0px;\n"
"    padding: 2px 2px 2px 2px;\n"
"    color: white;\n"
"}\n"
"\n"
"QLineEdit::hover {\n"
"    border-color:#63C2C4;\n"
"}")
        self.hotwordsLineEdit.setClearButtonEnabled(True)
        self.hotwordsLineEdit.setObjectName("hotwordsLineEdit")
        self.horizontalLayout_8.addWidget(self.hotwordsLineEdit)
        self.browseHotwordsButton = QtWidgets.QPushButton(self.frame_2)
        self.browseHotwordsButton.setEnabled(True)
        self.browseHotwordsButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.browseHotwordsButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(84, 84, 84);\n"
"    border-color: white\n"
"}")
        self.browseHotwordsButton.setText("")
        self.browseHotwordsButton.setIcon(icon)
        self.browseHotwordsButton.setAutoDefault(False)
        self.browseHotwordsButton.setObjectName("browseHotwordsButton")
        self.horizontalLayout_8.addWidget(self.browseHotwordsButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.verticalLayout_4.addWidget(self.frame_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.buttonBox = QtWidgets.QHBoxLayout()
        self.buttonBox.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.buttonBox.setContentsMargins(0, -1, -1, -1)
        self.buttonBox.setSpacing(6)
        self.buttonBox.setObjectName("buttonBox")
        self.resetButton = QtWidgets.QPushButton(OptionsDialog)
        self.resetButton.setMinimumSize(QtCore.QSize(135, 30))
        self.resetButton.setMaximumSize(QtCore.QSize(135, 30))
        self.resetButton.setStyleSheet("QPushButton {\n"
"    border-radius: 6px;\n"
"    border: 3px solid white;\n"
"\n"
"    font-weight: 600;\n"
"    font-size: 14px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-color: rgb(208, 208, 208); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(70, 70, 70);\n"
"}")
        self.resetButton.setAutoDefault(False)
        self.resetButton.setObjectName("resetButton")
        self.buttonBox.addWidget(self.resetButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonBox.addItem(spacerItem1)
        self.CancelButton = QtWidgets.QPushButton(OptionsDialog)
        self.CancelButton.setMinimumSize(QtCore.QSize(135, 30))
        self.CancelButton.setStyleSheet("QPushButton#CancelButton {\n"
"    border-radius: 6px;\n"
"    border: 3px solid #9C8ABF;\n"
"\n"
"    font-weight: 600;\n"
"    font-size: 14px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#CancelButton:hover {\n"
"    border-color: #B8A2E1; \n"
"}\n"
"\n"
"QPushButton#CancelButton:pressed {\n"
"    background-color: rgb(70, 70, 70);\n"
"}")
        self.CancelButton.setAutoDefault(False)
        self.CancelButton.setObjectName("CancelButton")
        self.buttonBox.addWidget(self.CancelButton)
        self.OKButton = QtWidgets.QPushButton(OptionsDialog)
        self.OKButton.setEnabled(True)
        self.OKButton.setMinimumSize(QtCore.QSize(135, 30))
        self.OKButton.setMaximumSize(QtCore.QSize(16777213, 16777215))
        self.OKButton.setStyleSheet("QPushButton#OKButton {\n"
"    border-radius: 6px;\n"
"    border: 3px solid #54a4a6;\n"
"\n"
"    font-weight: 600;\n"
"    font-size: 14px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#OKButton:hover {\n"
"   border-color: #63C2C4;\n"
"}\n"
"\n"
"QPushButton#OKButton:pressed {\n"
"    background-color: rgb(70, 70, 70)\n"
"}\n"
"\n"
"QPushButton#OKButton:disabled {\n"
"\n"
"    color: rgb(153, 153, 153);\n"
"}")
        self.OKButton.setAutoDefault(False)
        self.OKButton.setDefault(False)
        self.OKButton.setObjectName("OKButton")
        self.buttonBox.addWidget(self.OKButton)
        self.verticalLayout_4.addLayout(self.buttonBox)

        self.retranslateUi(OptionsDialog)
        self.OKButton.clicked.connect(OptionsDialog.accept)
        self.CancelButton.clicked.connect(OptionsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(OptionsDialog)

    def retranslateUi(self, OptionsDialog):
        _translate = QtCore.QCoreApplication.translate
        OptionsDialog.setWindowTitle(_translate("OptionsDialog", "Opcije"))
        self.label.setText(_translate("OptionsDialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:700; color:#ffffff;\">Osnovne postavke</span></p></body></html>"))
        self.micLabel.setText(_translate("OptionsDialog", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">MIkrofon:</span></p></body></html>"))
        self.apiLabel.setToolTip(_translate("OptionsDialog", "<html><head/><body><p>Svaki poslužitelj podržava neke od niže navedenih opcija.</p><p>Sphinx API radi offline.</p></body></html>"))
        self.apiLabel.setText(_translate("OptionsDialog", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Poslužitelj: </span></p></body></html>"))
        self.apiComboBox.setItemText(0, _translate("OptionsDialog", "Google (dev)"))
        self.apiComboBox.setItemText(1, _translate("OptionsDialog", "Google Cloud"))
        self.apiComboBox.setItemText(2, _translate("OptionsDialog", "PocketSphinx"))
        self.apiComboBox.setItemText(3, _translate("OptionsDialog", "Houndify"))
        self.durationLabel.setToolTip(_translate("OptionsDialog", "<html><head/><body><p>Slušanje će se prekinuti nakon navedenog vremena (HH:MM:SS).</p><p>Slušanje može trajati od 5s do 1h.</p></body></html>"))
        self.durationLabel.setText(_translate("OptionsDialog", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Trajanje govora:</span></p></body></html>"))
        self.durationLineEdit.setInputMask(_translate("OptionsDialog", "99:99:99"))
        self.durationLineEdit.setText(_translate("OptionsDialog", "00:00:05"))
        self.durationLineEdit.setPlaceholderText(_translate("OptionsDialog", "00:00"))
        self.label_3.setText(_translate("OptionsDialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:700; color:#ffffff;\">Postavke zvuka</span></p></body></html>"))
        self.noiseTypeLabel.setToolTip(_translate("OptionsDialog", "<html><head/><body><p>Vrijednosti više od praga se smatraju govorom, a niže tišinom.</p><p>Prag se može odrediti dinamički, s ili bez početne vrijednosti, ili postaviti na fiksnu vrijednost.</p></body></html>"))
        self.noiseTypeLabel.setText(_translate("OptionsDialog", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Prag pozadinske buke:</span></p></body></html>"))
        self.noiseTypeComboBox.setItemText(0, _translate("OptionsDialog", "Dinamički"))
        self.noiseTypeComboBox.setItemText(1, _translate("OptionsDialog", "Hibridni"))
        self.noiseTypeComboBox.setItemText(2, _translate("OptionsDialog", "Fiksni"))
        self.noiseValueLabel.setToolTip(_translate("OptionsDialog", "<html><head/><body><p>Ovisno o odabiru načina određivanja praga pozadinske buke ova vrijednost označava početnu(\'Hibridni\') ili stalnu(\'Fiksni\') vrijednost praga.</p></body></html>"))
        self.noiseValueLabel.setText(_translate("OptionsDialog", "<html><head/><body><p><span style=\" color:#ffffff;\">Vrijednost: </span></p></body></html>"))
        self.noiseValueLineEdit.setPlaceholderText(_translate("OptionsDialog", "0-4000"))
        self.label_2.setText(_translate("OptionsDialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:700; color:#ffffff;\">Jezične postavke</span></p></body></html>"))
        self.languageLabel.setText(_translate("OptionsDialog", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Jezik:</span></p></body></html>"))
        self.phrasesLabel.setToolTip(_translate("OptionsDialog", "<html><head/><body><p>Navedene riječi ili fraze će imati prednost prepoznavanja nad riječima koje slično zvuče. </p><p>Svaku frazu je potrebno navesti u posebnom retku.</p><p>U slučaju Sphinx poslužitelja, moguće je specificirati razinu osjetljivosti za svaku frazu, tako da se na kraju retka navede broj od 0 do 1.</p></body></html>"))
        self.phrasesLabel.setText(_translate("OptionsDialog", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Ključne riječi: </span></p></body></html>"))
        self.phrasesTextEdit.setPlaceholderText(_translate("OptionsDialog", "riječ/fraza osjetljivost"))
        self.sensitivityLabel.setToolTip(_translate("OptionsDialog", "<html><head/><body><p>Razina osjetljivosti za sve ključne riječi kojima osjetljivost nije ranije(gore) specificirana.</p><p>Veća osjetljivosti vodi ka \'češćem\' prepoznavanju i obrnuto.</p></body></html>"))
        self.sensitivityLabel.setText(_translate("OptionsDialog", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Razina osjetljivosti: </span></p></body></html>"))
        self.sensitivityLineEdit.setPlaceholderText(_translate("OptionsDialog", "0-1"))
        self.grammarLabel.setToolTip(_translate("OptionsDialog", "<html><head/><body><p>Datoteka u kojoj je definirana FSG ili JSGF gramatika.</p><p>Unos gramatike će se ignorirati ako su definirane ključne riječi.</p></body></html>"))
        self.grammarLabel.setText(_translate("OptionsDialog", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Gramatika:</span></p></body></html>"))
        self.hotwordLabel.setToolTip(_translate("OptionsDialog", "<html><head/><body><p>Datoteka koja opisuje model za prepoznavanje riječi koja će označavati početak govora.</p></body></html>"))
        self.hotwordLabel.setText(_translate("OptionsDialog", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Okidač:</span></p></body></html>"))
        self.resetButton.setText(_translate("OptionsDialog", "Reset"))
        self.CancelButton.setText(_translate("OptionsDialog", "Odustani"))
        self.OKButton.setText(_translate("OptionsDialog", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OptionsDialog = QtWidgets.QDialog()
    ui = Ui_OptionsDialog()
    ui.setupUi(OptionsDialog)
    OptionsDialog.show()
    sys.exit(app.exec())
