# Form implementation generated from reading ui file 'src/MenuWidget/MenuWidget.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MenuWidget(object):
    def setupUi(self, MenuWidget):
        MenuWidget.setObjectName("MenuWidget")
        MenuWidget.resize(800, 800)
        MenuWidget.setMaximumSize(QtCore.QSize(800, 800))
        MenuWidget.setStatusTip("")
        MenuWidget.setWhatsThis("")
        MenuWidget.setAccessibleName("")
        MenuWidget.setAccessibleDescription("")
        MenuWidget.setAutoFillBackground(False)
        MenuWidget.setStyleSheet("QWidget #MenuWidget {\n"
"    background-image: url(\"images:main-window.png\");\n"
"    background-attachment:  fixed;\n"
"}")
        self.RecordButton = QtWidgets.QPushButton(MenuWidget)
        self.RecordButton.setGeometry(QtCore.QRect(200, 120, 183, 183))
        self.RecordButton.setStyleSheet("QPushButton#RecordButton{\n"
"    border-radius: 91px;\n"
"    background:  rgb(84, 164, 166);\n"
"}\n"
"\n"
"QPushButton#RecordButton:hover {\n"
"    background: #63C2C4;\n"
"}\n"
"\n"
"QPushButton#RecordButton:pressed {\n"
"    background: #63C2C4;\n"
"    border: 3px solid white;\n"
"}\n"
"")
        self.RecordButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resources/icons/mic.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.RecordButton.setIcon(icon)
        self.RecordButton.setIconSize(QtCore.QSize(140, 140))
        self.RecordButton.setCheckable(True)
        self.RecordButton.setObjectName("RecordButton")
        self.LoadButton = QtWidgets.QPushButton(MenuWidget)
        self.LoadButton.setGeometry(QtCore.QRect(417, 481, 183, 183))
        self.LoadButton.setStyleSheet("QPushButton#LoadButton {\n"
"    border-radius: 91px;\n"
"    background: #9C8ABF;\n"
"}\n"
"\n"
"QPushButton#LoadButton:hover {\n"
"    background: #B8A2E1;\n"
"}\n"
"\n"
"QPushButton#LoadButton:pressed {\n"
"    background: #B8A2E1;\n"
"    border: 3px solid white;\n"
"}\n"
"")
        self.LoadButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../resources/icons/audio.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.LoadButton.setIcon(icon1)
        self.LoadButton.setIconSize(QtCore.QSize(150, 150))
        self.LoadButton.setCheckable(True)
        self.LoadButton.setObjectName("LoadButton")
        self.LoadButton.raise_()
        self.RecordButton.raise_()

        self.retranslateUi(MenuWidget)
        QtCore.QMetaObject.connectSlotsByName(MenuWidget)

    def retranslateUi(self, MenuWidget):
        _translate = QtCore.QCoreApplication.translate
        MenuWidget.setWindowTitle(_translate("MenuWidget", "Skripta"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MenuWidget = QtWidgets.QWidget()
    ui = Ui_MenuWidget()
    ui.setupUi(MenuWidget)
    MenuWidget.show()
    sys.exit(app.exec())
