# Form implementation generated from reading ui file 'src/View/OptionsDialog/OptionsDialog.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OptionsDialog(object):
    def setupUi(self, OptionsDialog):
        OptionsDialog.setObjectName("OptionsDialog")
        OptionsDialog.resize(550, 650)
        OptionsDialog.setStyleSheet("QDialog#OptionsDialog {\n"
"    background-color: rgb(84, 84, 84);\n"
"}")
        OptionsDialog.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(OptionsDialog)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fileHLayout = QtWidgets.QHBoxLayout()
        self.fileHLayout.setObjectName("fileHLayout")
        self.FileLabel = QtWidgets.QLabel(OptionsDialog)
        self.FileLabel.setObjectName("FileLabel")
        self.fileHLayout.addWidget(self.FileLabel)
        self.fileLineEdit = QtWidgets.QLineEdit(OptionsDialog)
        self.fileLineEdit.setText("")
        self.fileLineEdit.setReadOnly(False)
        self.fileLineEdit.setClearButtonEnabled(True)
        self.fileLineEdit.setObjectName("fileLineEdit")
        self.fileHLayout.addWidget(self.fileLineEdit)
        self.browseFileButton = QtWidgets.QPushButton(OptionsDialog)
        self.browseFileButton.setAutoFillBackground(False)
        self.browseFileButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(84, 84, 84);\n"
"    border-color: white\n"
"}")
        self.browseFileButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resources/icons/browse.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.browseFileButton.setIcon(icon)
        self.browseFileButton.setAutoDefault(False)
        self.browseFileButton.setFlat(False)
        self.browseFileButton.setObjectName("browseFileButton")
        self.fileHLayout.addWidget(self.browseFileButton)
        self.verticalLayout.addLayout(self.fileHLayout)
        self.timeHLayout = QtWidgets.QHBoxLayout()
        self.timeHLayout.setObjectName("timeHLayout")
        self.FromLabel = QtWidgets.QLabel(OptionsDialog)
        self.FromLabel.setObjectName("FromLabel")
        self.timeHLayout.addWidget(self.FromLabel)
        self.FromLineEdit = QtWidgets.QLineEdit(OptionsDialog)
        self.FromLineEdit.setEnabled(True)
        self.FromLineEdit.setMaximumSize(QtCore.QSize(61, 16777215))
        self.FromLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhTime)
        self.FromLineEdit.setDragEnabled(False)
        self.FromLineEdit.setObjectName("FromLineEdit")
        self.timeHLayout.addWidget(self.FromLineEdit)
        self.DashLabel = QtWidgets.QLabel(OptionsDialog)
        self.DashLabel.setMaximumSize(QtCore.QSize(20, 16777215))
        self.DashLabel.setStyleSheet("QLabel#DashLabel {\n"
"    padding-left: 5px;\n"
"}\n"
"    ")
        self.DashLabel.setObjectName("DashLabel")
        self.timeHLayout.addWidget(self.DashLabel)
        self.ToLineEdit = QtWidgets.QLineEdit(OptionsDialog)
        self.ToLineEdit.setEnabled(True)
        self.ToLineEdit.setMaximumSize(QtCore.QSize(61, 16777215))
        self.ToLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhTime)
        self.ToLineEdit.setDragEnabled(False)
        self.ToLineEdit.setObjectName("ToLineEdit")
        self.timeHLayout.addWidget(self.ToLineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.timeHLayout.addItem(spacerItem)
        self.timeHLayout.setStretch(0, 1)
        self.timeHLayout.setStretch(3, 1)
        self.timeHLayout.setStretch(4, 1)
        self.verticalLayout.addLayout(self.timeHLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QHBoxLayout()
        self.buttonBox.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.buttonBox.setContentsMargins(0, -1, -1, -1)
        self.buttonBox.setObjectName("buttonBox")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonBox.addItem(spacerItem2)
        self.CancelButton = QtWidgets.QPushButton(OptionsDialog)
        self.CancelButton.setMinimumSize(QtCore.QSize(135, 30))
        self.CancelButton.setStyleSheet("QPushButton#CancelButton {\n"
"    border-radius: 6px;\n"
"    border: 3px solid #9C8ABF;\n"
"\n"
"    font-weight: 600;\n"
"    font-size: 14px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#CancelButton:hover {\n"
"    border-color: #B8A2E1; \n"
"}\n"
"\n"
"QPushButton#CancelButton:pressed {\n"
"    background-color: rgb(70, 70, 70);\n"
"}")
        self.CancelButton.setAutoDefault(False)
        self.CancelButton.setObjectName("CancelButton")
        self.buttonBox.addWidget(self.CancelButton)
        self.OKButton = QtWidgets.QPushButton(OptionsDialog)
        self.OKButton.setEnabled(False)
        self.OKButton.setMinimumSize(QtCore.QSize(135, 30))
        self.OKButton.setMaximumSize(QtCore.QSize(16777213, 16777215))
        self.OKButton.setStyleSheet("QPushButton#OKButton {\n"
"    border-radius: 6px;\n"
"    border: 3px solid #54a4a6;\n"
"\n"
"    font-weight: 600;\n"
"    font-size: 14px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#OKButton:hover {\n"
"   border-color: #63C2C4;\n"
"}\n"
"\n"
"QPushButton#OKButton:pressed {\n"
"    background-color: rgb(70, 70, 70)\n"
"}\n"
"\n"
"QPushButton#OKButton:disabled {\n"
"\n"
"    color: rgb(153, 153, 153);\n"
"}")
        self.OKButton.setAutoDefault(False)
        self.OKButton.setDefault(False)
        self.OKButton.setObjectName("OKButton")
        self.buttonBox.addWidget(self.OKButton)
        self.verticalLayout.addLayout(self.buttonBox)

        self.retranslateUi(OptionsDialog)
        self.OKButton.clicked.connect(OptionsDialog.accept)
        self.CancelButton.clicked.connect(OptionsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(OptionsDialog)

    def retranslateUi(self, OptionsDialog):
        _translate = QtCore.QCoreApplication.translate
        OptionsDialog.setWindowTitle(_translate("OptionsDialog", "Opcije"))
        self.FileLabel.setText(_translate("OptionsDialog", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Datoteka: </span></p></body></html>"))
        self.FromLabel.setText(_translate("OptionsDialog", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Vremenski interval:</span></p></body></html>"))
        self.FromLineEdit.setInputMask(_translate("OptionsDialog", "99:99:99"))
        self.FromLineEdit.setText(_translate("OptionsDialog", "00:00:00"))
        self.FromLineEdit.setPlaceholderText(_translate("OptionsDialog", "00:00:00"))
        self.DashLabel.setText(_translate("OptionsDialog", "<html><head/><body><p><span style=\" font-size:12pt; color:#ffffff;\">   -</span></p></body></html>"))
        self.ToLineEdit.setInputMask(_translate("OptionsDialog", "99:99:99"))
        self.ToLineEdit.setText(_translate("OptionsDialog", "00:00:00"))
        self.ToLineEdit.setPlaceholderText(_translate("OptionsDialog", "00:00:00"))
        self.CancelButton.setText(_translate("OptionsDialog", "Odustani"))
        self.OKButton.setText(_translate("OptionsDialog", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OptionsDialog = QtWidgets.QDialog()
    ui = Ui_OptionsDialog()
    ui.setupUi(OptionsDialog)
    OptionsDialog.show()
    sys.exit(app.exec())
