# Form implementation generated from reading ui file 'ui/FormatErrorDialog.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UnsupportedFormatDialog(object):
    def setupUi(self, UnsupportedFormatDialog):
        UnsupportedFormatDialog.setObjectName("UnsupportedFormatDialog")
        UnsupportedFormatDialog.resize(500, 200)
        UnsupportedFormatDialog.setAccessibleName("")
        UnsupportedFormatDialog.setStyleSheet("QDialog#UnsupportedFormatDialog {\n"
"    background-color: rgb(84, 84, 84)\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(UnsupportedFormatDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.InvalidFormatLabel = QtWidgets.QLabel(UnsupportedFormatDialog)
        self.InvalidFormatLabel.setStyleSheet("QLabel#InvalidFormatLabel {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"}")
        self.InvalidFormatLabel.setObjectName("InvalidFormatLabel")
        self.verticalLayout.addWidget(self.InvalidFormatLabel)
        self.OKButton = QtWidgets.QPushButton(UnsupportedFormatDialog)
        self.OKButton.setStyleSheet("QPushButton#OKButton {\n"
"    margin-left: 160px;\n"
"    margin-right: 160px;\n"
"    padding-top: 10px;\n"
"    padding-bottom: 10px;\n"
"\n"
"    border-radius: 6px;\n"
"    border: 3px solid #54a4a6;\n"
"\n"
"    font-weight: 600;\n"
"    font-size: 14px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#OKButton:hover {\n"
"    border-color: #63C2C4;    \n"
"}\n"
"\n"
"QPushButton#OKButton:pressed {\n"
"    background-color: rgb(70, 70, 70)\n"
"}")
        self.OKButton.setObjectName("OKButton")
        self.verticalLayout.addWidget(self.OKButton)

        self.retranslateUi(UnsupportedFormatDialog)
        self.OKButton.clicked.connect(UnsupportedFormatDialog.close)
        QtCore.QMetaObject.connectSlotsByName(UnsupportedFormatDialog)

    def retranslateUi(self, UnsupportedFormatDialog):
        _translate = QtCore.QCoreApplication.translate
        UnsupportedFormatDialog.setWindowTitle(_translate("UnsupportedFormatDialog", "Greška"))
        self.InvalidFormatLabel.setText(_translate("UnsupportedFormatDialog", "<html><head/><body><p align=\"center\">Izabrana datoteka nije među podržanim formatima:<br>\n"
"WAV (PCM/LPCM), FLAC (nativni), AIFF i AIFF-C.</p></body></html>"))
        self.OKButton.setText(_translate("UnsupportedFormatDialog", "U redu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UnsupportedFormatDialog = QtWidgets.QDialog()
    ui = Ui_UnsupportedFormatDialog()
    ui.setupUi(UnsupportedFormatDialog)
    UnsupportedFormatDialog.show()
    sys.exit(app.exec())
